// JavaScript Document
;(function($,obj,config){
	obj.control.set({
		name:"indexB",
		par:[],
		fn:function(data){
			obj.model.get("#scroller","seguesOne","segues",function(model){
				model.show();
				model.goto("pageTwo",function(target,fn){
					obj.model.get(target,"testA","test",function(model){
						console.log(model)
						console.log(1)
					});
					obj.model.get(target,"testB","test",function(model){
						console.log(model)
						console.log(2)
						});
					obj.model.get(target,"testC","test",function(model){
						model.show();
						console.log(3)
						});
					obj.model.get(target,"testD","test",function(model){
						console.log(model)
						console.log(4)
						});
					fn();
					},{w:"1080px"});
					
				})
			}
		});
	})($,app,config);